### ISSUE TITLE
No module named 'cleanfid'**

### ISSUE THREAD

**Issue by Dr-zhang691** [GaParmar/img2img-turbo#102]
Please help solve it, thank you！！！
Traceback (most recent call last):
  File "/root/autodl-tmp/image/src/train_cyclegan_turbo.py", line 17, in <module>
    from cleanfid.fid import get_folder_features, build_feature_extractor, frechet_distance
**ModuleNotFoundError: No module named 'cleanfid'**
Traceback (most recent call last):
  File "/root/miniconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/root/miniconda3/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/root/miniconda3/lib/python3.12/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
**subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', 'src/train_cyclegan_turbo.py', '--pretrained_model_name_or_path=stabilityai/sd-turbo', '--output_dir=output/cyclegan_turbo/my_horse2zebra', '--dataset_folder', 'data/my_horse2zebra', '--train_img_prep', 'resize_286_randomcrop_256x256_hflip', '--val_img_prep', 'no_resize', '--learning_rate=1e-5', '--max_train_steps=25000', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--report_to', 'wandb', '--tracker_project_name', 'gparmar_unpaired_h2z_cycle_debug_v2', '--enable_xformers_memory_efficient_attention', '--validation_steps', '250', '--lambda_gan', '0.5', '--lambda_idt', '1', '--lambda_cycle', '1']' returned non-zero exit status 1.**

**Comment by GaParmar** [comment]
Hi, 

Could you check if the clean-fid library is installed in your environment by running the command `pip show clean-fid`? 

-Gaurav
