### ISSUE TITLE
Upgrade to latest SD model

### ISSUE THREAD

**Issue by zmingen** [GaParmar/img2img-turbo#105]
It's really great work. I saw that SD-turbo is used as base model, do you have plan to support SDXL-turbo or SD3.5?

**Comment by andjoer** [comment]
I did a fork and implemented so far SDXL and SD3.5 https://github.com/andjoer/img2img-turbo.git I tested it with the fill circles and the horse/zebra dataset and it works for both. But on SD3.5 it took over 5000 steps for the horses to become decent zebras. It's good that it works also with SD3.5 since it is flow matching and there is no one step version of it yet. I trained SD3.5 without skip layers and a frozen vae, otherwise training became unstable. The vae can be trained later, but the one from SD3.5 is good already, even without skips. This is the command to start cyclegan training with SD3.5:

```
accelerate launch src/train_cyclegan_turbo.py \
    --output_dir="output/cyclegan/horsezebra" \
    --model_type="sd3" \
    --cv_type="clip" \
    --pretrained_model_name_or_path="stabilityai/stable-diffusion-3.5-large-turbo"\
    --dataset_folder="data/my_horse2zebra" \
    --train_img_prep="resize_256" \
    --val_img_prep="resize_256" \
    --train_batch_size=1 \
    --gradient_accumulation_steps=4 \
    --viz_freq 50 \
    --max_train_steps=20000 \
    --learning_rate=5e-6 \
    --no_skips \
    --freeze_vae \
    --lora_rank_unet=8 \
    --lambda_gan=4 \
    --checkpointing_steps 2000 \
    --validation_steps 250 \
    --enable_xformers_memory_efficient_attention \
    --report_to "wandb" --tracker_project_name "cycleGan_horse" \
```

It still needs to be figured out which lora ranks, lambdas etc. are working best for SD3.5, so I would be happy to hear if it worked for your dataset.

**Comment by Aike2071** [comment]
Hi,@andjoer ,
I'm using your implementation but encountered an error,could you give me some guidance to slove this?
``
Traceback (most recent call last):
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 920, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/diffusers/models/autoencoders/__init__.py", line 1, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_asym_kl.py", line 22, in <module>
    from ..modeling_utils import ModelMixin
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 35, in <module>
    from ..quantizers import DiffusersAutoQuantizer, DiffusersQuantizer
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/diffusers/quantizers/__init__.py", line 15, in <module>
    from .auto import DiffusersAutoQuantizer
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/diffusers/quantizers/auto.py", line 31, in <module>
    from .torchao import TorchAoHfQuantizer
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/diffusers/quantizers/torchao/__init__.py", line 15, in <module>
    from .torchao_quantizer import TorchAoHfQuantizer
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/diffusers/quantizers/torchao/torchao_quantizer.py", line 57, in <module>
    torch.float8_e4m3fn,
AttributeError: module 'torch' has no attribute 'float8_e4m3fn'
``

**Comment by andjoer** [comment]
Hi,

Thanks for giving my implementation a try. The error you’re encountering seems to originate from the diffusers library rather than the training scripts themselves. Specifically, the traceback shows that diffusers is trying to access torch.float8_e4m3fn, which isn’t available in your current PyTorch version—this usually points to a version mismatch. I recommend ensuring that you're using PyTorch 2.2 or later, as that update includes the necessary attribute. However I did not use quantized models in my test and would recommend to train with the non quantized versions.

**Comment by Aike2071** [comment]
Thanks for the reply! My current pytorch version is 2.0 as the environment.yml writes. I don’t know I am using quantized model, I simply git cloned your implementation and used the command like this you mentioned:


> 
> ```
> accelerate launch src/train_cyclegan_turbo.py \
>     --output_dir="output/cyclegan/horsezebra" \
>     --model_type="sd3" \
>     --cv_type="clip" \
>     --pretrained_model_name_or_path="stabilityai/stable-diffusion-3.5-large-turbo"\
>     --dataset_folder="data/my_horse2zebra" \
>     --train_img_prep="resize_256" \
>     --val_img_prep="resize_256" \
>     --train_batch_size=1 \
>     --gradient_accumulation_steps=4 \
>     --viz_freq 50 \
>     --max_train_steps=20000 \
>     --learning_rate=5e-6 \
>     --no_skips \
>     --freeze_vae \
>     --lora_rank_unet=8 \
>     --lambda_gan=4 \
>     --checkpointing_steps 2000 \
>     --validation_steps 250 \
>     --enable_xformers_memory_efficient_attention \
>     --report_to "wandb" --tracker_project_name "

**Comment by andjoer** [comment]
Thanks for pointing this out. Since I forked the original code I left some parts unchanged but I will delete the yaml file in a future version. The yaml environment is still the one used in the original img2img-turbo code, please install the requirements.txt into your virtual environment. 
The next thing would be to check the accelerate configuration, on Mac its on ~/.cache/huggingface/accelerate/default_config.yaml

**Comment by Aike2071** [comment]
I re-installed packages in the requirements.txt.One thing strange is that it downloaded Pytorch version ranging from 2.6.0 to 2.0.1,is that an unexpected accident or it is how things go?

**Comment by andjoer** [comment]
Thanks for this observation. It looks like two packaging demanding an other PyTorch version but are compatible at the end. It's not optimal, I will need to do the requirements from scratch at some point. Does it work now?

**Comment by Aike2071** [comment]
The training can now run properly.In the requirements,PyTorch and some cuda dependencies will be downloaded multiple times in different version,but I didn't see any error besides the environment taking up more space.Thanks again for the help and great implementation!
