### ISSUE TITLE
keyerror:no clip_txt_model

### ISSUE THREAD

**Issue by a1122446488** [GaParmar/img2img-turbo#11]
When I run Python gradio_canny2image.py, keyerror: no clip_txt_model appears. How should I download this

**Comment by GaParmar** [comment]
Hi, 

Could you provide the exact error message that you encountered? 

-Gaurav

**Comment by a1122446488** [comment]
Hello, I'm here https://huggingface.co/stabilityai/sd-turbo/tree/main Download relevant files directly from the website, but encounter these issues during runtime Traceback (most recent call last):
Traceback (most recent call last):
  File "E:\Codes\sc\img2img-turbo-main\img2img-turbo-main\gradio_canny2image.py", line 8, in <module>
    model = Pix2Pix_Turbo("edge_to_image")
  File "E:\Codes\sc\img2img-turbo-main\img2img-turbo-main\src\pix2pix_turbo.py", line 31, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained("stabilityai/sd-turbo", subfolder="tokenizer")
  File "C:\ProgramData\anaconda3\envs\img2img-turbo\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 733, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "C:\ProgramData\anaconda3\envs\img2img-turbo\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1064, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "C:\ProgramData\anaconda3\envs\img2img-turbo\lib\site-packages\transformers\models\auto\configuration_auto.py", line 761, in __getitem__
    raise KeyError(key)
KeyError: 'clip_text_model'

**Comment by GaParmar** [comment]
It looks like you have some issues with downloading the SD-Turbo model. 
Could you try deleting the cached sd-turbo model and run these commands to see if it gets downloaded correctly:
```
from diffusers import AutoencoderKL, UNet2DConditionModel
tokenizer = AutoTokenizer.from_pretrained("stabilityai/sd-turbo", subfolder="tokenizer")
```

**Comment by a1122446488** [comment]
Is the download of the SD Tyrbo model from https://huggingface.co/stabilityai/sd-turbo/tree/main Just install all of them directly and create them in the stablityai file?

**Comment by GaParmar** [comment]
You should not need to download the model manually from the website. 
The model should get downloaded automatically when you run the command above.

**Comment by a1122446488** [comment]
But when I run Python graphic_cannoy2image.py without downloading it, Traceback (most recent call last) will appear:
  File "E:\Codes\sc\img2img-turbo-main\img2img-turbo-main\gradio_canny2image.py", line 8, in <module>
    model = Pix2Pix_Turbo("edge_to_image")
  File "E:\Codes\sc\img2img-turbo-main\img2img-turbo-main\src\pix2pix_turbo.py", line 31, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained("stabilityai/sd-turbo", subfolder="tokenizer")
  File "C:\ProgramData\anaconda3\envs\img2img-turbo\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 733, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "C:\ProgramData\anaconda3\envs\img2img-turbo\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1048, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\ProgramData\anaconda3\envs\img2img-turbo\lib\site-packages\transformers\configuration_utils.py", line 622, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\ProgramData\anaconda3\envs\img2img-turbo\lib\site-packages\transformers\configuration_utils.py", line 677, in _get_config_dict
    resolved_config_file = cached_file(
  File "C:\ProgramData\anaconda3\envs\img2img-turbo\lib\site-packages\transformers\utils\hub.py", line 470, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like stabilityai/sd-turbo is not the path to a directory containing a file named tokenizer\config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by GaParmar** [comment]
Ah, that is unexpected, maybe you have some network connection issues?

**Comment by a1122446488** [comment]
So I can just go straight to the https://huggingface.co/stabilityai/sd-turbo/tree/main Is it running after manual installation on?

**Comment by GaParmar** [comment]
I have not tried using huggingface in offline mode. 
Maybe this thread might be helpful?
https://github.com/huggingface/transformers/issues/11231

**Comment by a1122446488** [comment]
Okay, I'll give it a try. Thank you very much

**Comment by wangwenqiao666** [comment]
https://www.cs.cmu.edu/~img2img-turbo/models/sketch_to_image_stochastic_lora.pkl
https://www.cs.cmu.edu/~img2img-turbo/models/edge_to_image_loras.pkl
download model in ./checkpoints.

**Comment by 447425299** [comment]
Hello, @a1122446488 ，
I was wondering if you had managed to resolve the issue mentioned above. If indeed you have, I would greatly appreciate it if you could kindly share the steps you took to arrive at a solution.

Thank you very much for your assistance.

**Comment by kanekiCY** [comment]
I also encountered the same problem in offline mode. I tried changing multiple transformer versions but couldn't solve it. Has anyone solved it？

**Comment by kanekiCY** [comment]
> Hello, @a1122446488 ， I was wondering if you had managed to resolve the issue mentioned above. If indeed you have, I would greatly appreciate it if you could kindly share the steps you took to arrive at a solution.
> 
> Thank you very much for your assistance.

This problem can be solved by downloading all the files in the SD Turbo directory and organizing them according to the directory format on the webpage.
