### ISSUE TITLE
OSError: stabilityai/sd-turbo does not appear to have a file named diffusion_pytorch_model.bin.

### ISSUE THREAD

**Issue by Vigneshwar73** [GaParmar/img2img-turbo#112]
OSError: stabilityai/sd-turbo does not appear to have a file named diffusion_pytorch_model.bin.
Traceback (most recent call last):
  File "/home/mad_lab/sim2real/img2img-turbo/turbo/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/mad_lab/sim2real/img2img-turbo/turbo/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/mad_lab/sim2real/img2img-turbo/turbo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/home/mad_lab/sim2real/img2img-turbo/turbo/lib/python3.10/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/mad_lab/sim2real/img2img-turbo/turbo/bin/python3', 'src/train_cyclegan_turbo.py', '--pretrained_model_name_or_path=stabilityai/sd-turbo', '--output_dir=output/cyclegan_turbo/my_horse2zebra', '--dataset_folder', 'data/my_horse2zebra', '--train_img_prep', 'resize_286_randomcrop_256x256_hflip', '--val_img_prep', 'no_resize', '--learning_rate=1e-5', '--max_train_steps=25000', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--report_to', 'wandb', '--tracker_project_name', 'gparmar_unpaired_h2z_cycle_debug_v3', '--enable_xformers_memory_efficient_attention', '--validation_steps', '250', '--lambda_gan', '0.5', '--lambda_idt', '1', '--lambda_cycle', '1']' returned non-zero exit status 1.

This is the error I am getting while trying to perform cycleGAN-turbo unpaired training on horse2zebra dataset

**Comment by GaParmar** [comment]
It looks like your machine cannot successfully connect to the huggingface repository. 
Could you try running these two lines to see if you can download the SD-turbo model successfully? 
```
from diffusers import UNet2DConditionModel
unet = UNet2DConditionModel.from_pretrained("stabilityai/sd-turbo", subfolder="unet")
```

**Comment by yassineAlouini** [comment]
How did you get the files on your `sd-turbo` folder @comPoserzz? Check the ones here to make sure you have the correct ones: https://huggingface.co/stabilityai/sd-turbo/tree/main
Also, you will probably need to change the path when calling:

`UNet2DConditionModel.from_pretrained("stabilityai/sd-turbo", subfolder="unet")`

to

`UNet2DConditionModel.from_pretrained("local/path/to/sd-turbo", subfolder="unet")`

**Comment by comPoserzz** [comment]
> How did you get the files on your `sd-turbo` folder [@comPoserzz](https://github.com/comPoserzz)? Check the ones here to make sure you have the correct ones: https://huggingface.co/stabilityai/sd-turbo/tree/main Also, you will probably need to change the path when calling:
> 
> `UNet2DConditionModel.from_pretrained("stabilityai/sd-turbo", subfolder="unet")`
> 
> to
> 
> `UNet2DConditionModel.from_pretrained("local/path/to/sd-turbo", subfolder="unet")`

Thank you for your reply! I’ve figured it out now. It was probably due to an incorrect path during the call. Thanks again for your response, and I wish you all the best!

**Comment by yassineAlouini** [comment]
That's great @comPoserzz. 
I guess we can close this @GaParmar?
