### ISSUE TITLE
inference_paired.py produces Error: AttributeError: 'AutoencoderKL' object has no attribute 'add_adapter'

### ISSUE THREAD

**Issue by grant541** [GaParmar/img2img-turbo#15]
Hello I am trying to run the inference_paired.py file on Windows, I have installed Diffusers==0.27.2 but there appears to be a missing function:

```
python inference_paired.py --model_name "edge_to_image"   --input_image "C:\Users\Stanford\Desktop\Img2Img\assets\examples\bird.png"  --prompt "a blue bird"  --output_dir "outputs"
Traceback (most recent call last):
  File "C:\Users\Stanford\Desktop\Img2Img\src\inference_paired.py", line 29, in <module>
    model = Pix2Pix_Turbo(pretrained_name=args.model_name, pretrained_path=args.model_path)
  File "C:\Users\Stanford\Desktop\Img2Img\src\pix2pix_turbo.py", line 69, in __init__
    vae.add_adapter(vae_lora_config, adapter_name="vae_skip")
  File "c:\Python39\lib\site-packages\diffusers\models\modeling_utils.py", line 218, in __getattr__
    return super().__getattr__(name)
  File "c:\Python39\lib\site-packages\torch\nn\modules\module.py", line 1704, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'AutoencoderKL' object has no attribute 'add_adapter'
```

Is this a bug? Which version of Diffusers is img2img-turbo expecting?

Thanks

**Comment by grant541** [comment]
Solved by installing a earlier version of Diffusers  

`pip install diffusers==0.25.1`
