### ISSUE TITLE
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like stabilityai/sd-turbo is not the path to a directory containing a file named tokenizer/config.json.

### ISSUE THREAD

**Issue by sun11711** [GaParmar/img2img-turbo#96]
Traceback (most recent call last):
  File "/root/autodl-tmp/img2img-turbo-main/src/train_cyclegan_turbo.py", line 390, in <module>
    main(args)
  File "/root/autodl-tmp/img2img-turbo-main/src/train_cyclegan_turbo.py", line 32, in main
    tokenizer = AutoTokenizer.from_pretrained("stabilityai/sd-turbo", subfolder="tokenizer", use_fast=False,)
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 733, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1048, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/transformers/configuration_utils.py", line 622, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/transformers/configuration_utils.py", line 677, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/miniconda3/envs/img2img-turbo/lib/python3.10/site-packages/transformers/utils/hub.py", line 470, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like stabilityai/sd-turbo is not the path to a directory containing a file named tokenizer/config.json.

![微信截图_20241020192142](https://github.com/user-attachments/assets/17c13aef-17ee-4a5d-bf84-5065c186ab75)
The stableai/sd-turbo folder does not contain the path to a directory with a file named tokenizer/config.json. What should we do?

**Comment by sun11711** [comment]
I have solved this problem.

**Comment by sun11711** [comment]
I have this problem is mainly a problem with the network connection, the solution you can refer to the following website.
https://blog.csdn.net/m0_61474277/article/details/140348032




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月30日(星期三) 下午2:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GaParmar/img2img-turbo] OSError: We couldn&#39;t connect to &#39;https://huggingface.co&#39; to load this file, couldn&#39;t find it in the cached files and it looks like stabilityai/sd-turbo is not the path to a directory containing a file named tokenizer/config.json. (Issue #96)















我已经解决了这个问题。

你能告诉我怎么解决吗？

-
直接回复这封邮件，在GitHub上查看，或取消订阅.
***@***.*** &gt;

**Comment by beiqiqi** [comment]
请问你是怎样解决的啊

**Comment by shendulcf** [comment]
> 请问你是怎样解决的啊
import os
os.environ['HF_ENDPOINT'] = 'https://hf-mirror.com'
